/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Clases.Operacion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class ConsultaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaUsuario
     */
    public ConsultaUsuario() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //setdatosUsuario();

    }
    
    public Image getIconImage(){
     Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/mi_logo.png"));   
      return retValue;   
    }
    
    public void setdatosUsuario(){
        Operacion op = new Operacion();
        op.getDatosUsuario(lb_cerrar.getText(), tabla_Ualumnos);
    }
    
    public void getDatoTabla(){
        int fila = tabla_Ualumnos.getSelectedRow();
        String nombreA = tabla_Ualumnos.getValueAt(fila, 2).toString();
        lb_nombreA.setText(nombreA);
        String paternoA = tabla_Ualumnos.getValueAt(fila, 3).toString();
        lb_paternoA.setText(paternoA);
        String maternoA = tabla_Ualumnos.getValueAt(fila, 4).toString();
        lb_maternoA.setText(maternoA);
        String edad = tabla_Ualumnos.getValueAt(fila, 5).toString();
        lb_edad.setText(edad);
        String nombreT = tabla_Ualumnos.getValueAt(fila, 7).toString();
        lb_nombreT.setText(nombreT);
        String paternoT = tabla_Ualumnos.getValueAt(fila, 8).toString();
        lb_paternoT.setText(paternoT);
        String maternoT = tabla_Ualumnos.getValueAt(fila, 9).toString();
        lb_maternoT.setText(maternoT);
        String telE = tabla_Ualumnos.getValueAt(fila, 12).toString();
        lb_telE.setText(telE);
        String tel = tabla_Ualumnos.getValueAt(fila, 11).toString();
        lb_tel.setText(tel);
        String direccion = tabla_Ualumnos.getValueAt(fila, 10).toString();
        lb_direccion.setText(direccion);
        String nivel = tabla_Ualumnos.getValueAt(fila, 14).toString();
        lb_nivel.setText(nivel);
        String total = tabla_Ualumnos.getValueAt(fila, 17).toString();
        lb_total.setText(total);
        
        String grupo = tabla_Ualumnos.getValueAt(fila, 15).toString();
        lb_grupo.setText(grupo);
        String turno = tabla_Ualumnos.getValueAt(fila, 13).toString();
        lb_turno.setText(turno);
        String alimentacion = tabla_Ualumnos.getValueAt(fila, 16).toString();
        int sub = Integer.parseInt(total);
        
        if(alimentacion.equals("NULL")){
            area_especial.setVisible(false);
            area_especial.setText("");
            lb_subtotal.setText(total);
        }else{
            area_especial.setVisible(true);
            area_especial.setText(alimentacion);
            lb_subtotal.setText(""+(sub-100));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_edad = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lbto1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        lb_cerrar = new javax.swing.JLabel();
        lb_paternoA = new javax.swing.JLabel();
        lb_subtotal = new javax.swing.JLabel();
        lb_paternoT = new javax.swing.JLabel();
        lb_maternoT = new javax.swing.JLabel();
        lb_telE = new javax.swing.JLabel();
        lb_tel = new javax.swing.JLabel();
        lb_nombreT = new javax.swing.JLabel();
        lb_nivel = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        lb_grupo = new javax.swing.JLabel();
        lb_turno = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        lb_nombreA = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btn_registar = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital San Rafael - Eventos");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1380, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EVENTOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        lb_edad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lb_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 50, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONSULTA DE DATOS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        lbto1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbto1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel3.add(lbto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONSULTA DE DATOS");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, -1, -1));

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(0, 0, 102));
        jPanel5.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(102, 102, 255));
        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONSULTA DE DATOS");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(0, 0, 102));
        jPanel7.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(0, 0, 102));
        jPanel7.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, -1, -1));

        jLabel116.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(0, 0, 102));
        jPanel7.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 520, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel9MouseMoved(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel9MouseReleased(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 102, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONSULTA DE DATOS");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 70));

        lb_direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 400, 10));

        jLabel137.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(0, 0, 102));
        jPanel9.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        lb_cerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_cerrarMouseClicked(evt);
            }
        });
        jPanel9.add(lb_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 20));

        lb_paternoA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_paternoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        lb_subtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 140, 10));

        lb_paternoT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_paternoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 140, 10));

        lb_maternoT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_maternoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 140, 10));

        lb_telE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_telE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 140, 10));

        lb_tel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 140, 10));

        lb_nombreT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_nombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 140, 10));

        lb_nivel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 150, 10));

        lb_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 140, 10));

        lb_grupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 140, 10));

        lb_turno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 150, 10));

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 0, 102));
        jPanel9.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, -1, -1));

        lb_nombreA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(lb_nombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 140, 10));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 0));
        jLabel29.setText("TIPO DE EVENTO");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        btn_registar.setBackground(new java.awt.Color(153, 0, 0));
        btn_registar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_registar.setText("REGRESAR");
        btn_registar.setBorder(null);
        btn_registar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registarActionPerformed(evt);
            }
        });
        jPanel9.add(btn_registar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 240, 40));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRATIVO" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n DESCRIPCION . . .\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 830, 280));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 730));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel9MouseReleased

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel9MouseMoved

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btn_registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registarActionPerformed
        // TODO add your handling code here:
        if(RevisaCampos()==false){
            RegistroInfante();
            toclean();
        }
    }//GEN-LAST:event_btn_registarActionPerformed

    private void lb_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_cerrarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "¡ HASTA PRONTO !","EXIT",JOptionPane.INFORMATION_MESSAGE);
        dispose();
        Login lg = new Login();
        lg.setVisible(true);

    }//GEN-LAST:event_lb_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registar;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_cerrar;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_edad;
    private javax.swing.JLabel lb_grupo;
    private javax.swing.JLabel lb_maternoT;
    private javax.swing.JLabel lb_nivel;
    private javax.swing.JLabel lb_nombreA;
    private javax.swing.JLabel lb_nombreT;
    private javax.swing.JLabel lb_paternoA;
    private javax.swing.JLabel lb_paternoT;
    private javax.swing.JLabel lb_subtotal;
    private javax.swing.JLabel lb_tel;
    private javax.swing.JLabel lb_telE;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_turno;
    private javax.swing.JLabel lbto1;
    // End of variables declaration//GEN-END:variables
}
