/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ERNESTO FLORES
 */
public class PRODUCTOS2 extends javax.swing.JFrame implements Runnable{
 String hora,minutos,segundos;
    Thread hilo;
    
     
    /**
     * Creates new form PRODUCTOS2
     */
    public PRODUCTOS2() {
        initComponents();
        eua.setText("0");
        aux.requestFocus();
        mostrar("");
       txt_precioto.setEnabled(false);
       
        
        this.setLocationRelativeTo(null);
        lfecha.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        
    }
    
  
    
    public Image getIconImage(){
     Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/k.png.jpg"));   
      return retValue;   
    }
     public void hora(){
        
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date ();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
      public void run(){
        Thread current =  Thread.currentThread();
        while (current == hilo){
            hora();
            lhora.setText(hora+":"+minutos+":"+segundos);
        }
    }
     
        

    void mostrar (String valor){
        
        String titulos [] = {"ID","CLAVE","PRODUCTO","EXISTENCIA","UNIDADES","UBICACION","PRECIO","PRECIO USD","PRECIO TOTAL","HORA","FECHA", "PROVEEDOR"};
        String [] registros = new String [12];
        String sql = "SELECT * FROM inventario where CONCAT (CLAVE, ' ',PRODUCTO   ) LIKE '%"+valor+"%'";
        DefaultTableModel model = new DefaultTableModel(null, titulos);
        clase cn = new clase();
        Connection cc = cn.Connetar();
        
        try {
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
               registros [0] = rs.getString("ID");
               registros [1] = rs.getString("CLAVE");
               registros [2] = rs.getString("PRODUCTO");
               registros [3] = rs.getString("EXISTENCIA");
               registros [4] = rs.getString("UNIDADES");
                registros [5] = rs.getString("UBICACION");
                  registros [6] = rs.getString("PRECIO");
                  registros [7] = rs.getString("PRECIO_USD");
               registros [8] = rs.getString("PRECIOT");
                registros [9] = rs.getString("HORA");
               registros [10] = rs.getString("FECHA");
               registros [11] = rs.getString("PROVEEDOR");
             
             
               
               
              
               
               model.addRow(registros);
            }
            tablap.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(PRODUCTOS2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_act = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_existencia1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_producto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cla = new javax.swing.JTextField();
        txt_ubicacion1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        txt_precioto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aux = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LCOSTOT = new javax.swing.JLabel();
        lhora = new javax.swing.JLabel();
        lfecha = new javax.swing.JLabel();
        txt_uni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_proveedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        eua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_costoeu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVENTARIO");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablap.setRowHeight(25
        );
        jScrollPane1.setViewportView(tablap);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1320, 220));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CLAVE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_act.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_act.setText("GUARDAR");
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });
        jPanel1.add(btn_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 120, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("ALTA / BAJA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("< Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 19));

        txt_existencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_existencia1ActionPerformed(evt);
            }
        });
        txt_existencia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_existencia1KeyPressed(evt);
            }
        });
        jPanel1.add(txt_existencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("EXISTENCIA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txt_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productoActionPerformed(evt);
            }
        });
        txt_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_productoKeyReleased(evt);
            }
        });
        jPanel1.add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PRODUCTO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txt_cla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claActionPerformed(evt);
            }
        });
        txt_cla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_claKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, -1));

        txt_ubicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ubicacion1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ubicacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("UBICACION:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("PRECIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        txt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_precioKeyPressed(evt);
            }
        });
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, -1));

        txt_precioto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_precioto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_preciotoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_precioto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 170, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_32px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("S E A R C H . . . .");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 100, -1));

        aux.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                auxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auxKeyReleased(evt);
            }
        });
        jPanel1.add(aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("COSTO TOTAL:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        LCOSTOT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(LCOSTOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 270, 10));

        lhora.setText("00:00:00");
        jPanel1.add(lhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lfecha.setText("DD/MM/YYYY");
        jPanel1.add(lfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        txt_uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uniActionPerformed(evt);
            }
        });
        jPanel1.add(txt_uni, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("UNIDADES:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("PROVEEDOR:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        txt_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proveedorActionPerformed(evt);
            }
        });
        txt_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_proveedorKeyPressed(evt);
            }
        });
        jPanel1.add(txt_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("VALOR DEL DOLAR:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        eua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euaActionPerformed(evt);
            }
        });
        eua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                euaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euaKeyReleased(evt);
            }
        });
        jPanel1.add(eua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("MNX");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        txt_costoeu.setText("jTextField1");
        jPanel1.add(txt_costoeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 0, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void auxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auxKeyPressed
        char car = evt.getKeyChar();
        jLabel8.setText("");
    }//GEN-LAST:event_auxKeyPressed

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
        float p,e,r,DOLAR,CD;
        p=Float.parseFloat(txt_precio.getText());
        e=Float.parseFloat(txt_existencia1.getText());
        DOLAR=Float.parseFloat(eua.getText());
        
        r=(p*e);
        CD=r*DOLAR;
     txt_costoeu.setText(String.valueOf(CD));
        txt_precioto.setText(String.valueOf(r));
        
        clase cn = new clase();
 Connection cc = cn.Connetar();
        String clave,producto,existencia,ubicacion,fechas,horas,pre,pret,unidad,PRO,dol;
        String sql="";
       
        clave=txt_cla.getText();
        producto=txt_producto.getText();
        existencia=txt_existencia1.getText();
        ubicacion=txt_ubicacion1.getText();
        fechas=lfecha.getText();
        horas=lhora.getText();
        pre=txt_precio.getText();
        pret=txt_precioto.getText();
        unidad=txt_uni.getText();
        PRO=txt_proveedor.getText();
        dol=txt_costoeu.getText();
       
        
        sql="INSERT INTO inventario (CLAVE, PRODUCTO, EXISTENCIA, UNIDADES, UBICACION, PRECIO, PRECIO_USD, PRECIOT, FECHA, HORA, PROVEEDOR) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        
        try {
            PreparedStatement pst = cc.prepareStatement(sql);
            pst.setString(1, clave);
            pst.setString(2, producto);
            pst.setString(3, existencia);
            pst.setString(4, unidad);
            pst.setString(5, ubicacion);
            pst.setString(6, pre);
            pst.setString(7, dol);
            pst.setString(8, pret);
            pst.setString(9, fechas);
            pst.setString(10, horas);
            pst.setString(11, PRO);
           
            if(clave.isEmpty() || producto.isEmpty() || existencia.isEmpty() || ubicacion.isEmpty() || pre.isEmpty() || dol.isEmpty()  ){
                JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS", "ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
            int n = pst.executeUpdate();   
            mostrar("");
              costot();
            
          txt_cla.setText("");
          txt_producto.setText("");
          txt_ubicacion1.setText("");
          txt_existencia1.setText("");
          txt_uni.setText("");
          txt_precio.setText("");
          txt_precioto.setText("");
          txt_proveedor.setText("");
          txt_cla.requestFocus();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PRODUCTOS2.class.getName()).log(Level.SEVERE, null, ex);
        }
     

    }//GEN-LAST:event_btn_actActionPerformed

    void costot(){
         LCOSTOT.setText("0");
       int ta = tablap.getRowCount();
       int c =0;
    
      
       do
           try {
              int f = c++;
              float n1 = Float.parseFloat(tablap.getValueAt(f, 6).toString());

              String nu = LCOSTOT.getText();

              double nu2;
           nu2 = Double.parseDouble(nu);
              float re = (float) (n1+nu2);
              
              
             
              LCOSTOT.setText(String.valueOf(re));
           } catch (Exception e) {
               
           }
           
           
           while(c<ta);
    }
    
    
    
    
    
    
    
    private void txt_claActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claActionPerformed
txt_producto.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claActionPerformed

    private void txt_ubicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ubicacion1ActionPerformed
 txt_existencia1.requestFocus();
    }//GEN-LAST:event_txt_ubicacion1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


 
       
       
       
       entrada_salida es = new entrada_salida();
       es.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productoActionPerformed
     txt_ubicacion1.requestFocus(); 
       
    }//GEN-LAST:event_txt_productoActionPerformed

    private void txt_existencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_existencia1ActionPerformed
txt_uni.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_txt_existencia1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        menu2 mn=new  menu2();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void auxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auxKeyReleased
mostrar(aux.getText());    


// TODO add your handling code here:
    }//GEN-LAST:event_auxKeyReleased

    private void txt_existencia1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_existencia1KeyPressed
 // TODO add your handling code here:
    }//GEN-LAST:event_txt_existencia1KeyPressed

    private void txt_claKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claKeyReleased
mostrar(txt_cla.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_txt_claKeyReleased

    private void txt_productoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productoKeyReleased
       mostrar(txt_producto.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_txt_productoKeyReleased

    private void txt_preciotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_preciotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_preciotoActionPerformed

    private void txt_precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_precioKeyPressed
    
    }//GEN-LAST:event_txt_precioKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        costot();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uniActionPerformed
txt_precio.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uniActionPerformed

    private void txt_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proveedorActionPerformed

    private void euaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_euaActionPerformed

    private void txt_proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proveedorKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        float p,e,r,dolar,cd;
        p=Float.parseFloat(txt_precio.getText());
        e=Float.parseFloat(txt_existencia1.getText());
        r=(p*e);
        dolar=Float.parseFloat(eua.getText());
        cd=r*dolar;
        txt_costoeu.setText(String.valueOf(cd));
        txt_precioto.setText(String.valueOf(r));
        
        clase cn = new clase();
 Connection cc = cn.Connetar();
        String clave,producto,existencia,ubicacion,fechas,horas,pre,pret,unidad,pro,PREUSD;
        String sql="";
       
        clave=txt_cla.getText();
        producto=txt_producto.getText();
        existencia=txt_existencia1.getText();
        ubicacion=txt_ubicacion1.getText();
        fechas=lfecha.getText();
        horas=lhora.getText();
        pre=txt_precio.getText();
        PREUSD=txt_costoeu.getText();
        pret=txt_precioto.getText();
        unidad=txt_uni.getText();
        pro=txt_proveedor.getText();
       
        
        sql="INSERT INTO inventario (CLAVE, PRODUCTO, EXISTENCIA, UNIDADES, UBICACION, PRECIO, PRECIO_USD, PRECIOT, FECHA, HORA, PROVEEDOR) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        
        try {
            PreparedStatement pst = cc.prepareStatement(sql);
            pst.setString(1, clave);
            pst.setString(2, producto);
            pst.setString(3, existencia);
            pst.setString(4, unidad);
            pst.setString(5, ubicacion);
            pst.setString(6, pre);
            pst.setString(7, PREUSD);
            pst.setString(8, pret);
            pst.setString(9, fechas);
            pst.setString(10, horas);
            pst.setString(11, pro);
           
            if(clave.isEmpty() || producto.isEmpty() || existencia.isEmpty() || ubicacion.isEmpty() || pre.isEmpty()  ){
                JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS", "ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
            int n = pst.executeUpdate();   
            mostrar("");
              costot();
            
          txt_cla.setText("");
          txt_producto.setText("");
          txt_ubicacion1.setText("");
          txt_existencia1.setText("");
          txt_uni.setText("");
          txt_precio.setText("");
          txt_precioto.setText("");
          txt_proveedor.setText("");
          txt_cla.requestFocus();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PRODUCTOS2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    }//GEN-LAST:event_txt_proveedorKeyPressed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
txt_proveedor.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void euaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euaKeyPressed
       
    }//GEN-LAST:event_euaKeyPressed

    private void euaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euaKeyReleased
//  LCOSTOT.setText("0");
//       int ta = tablap.getRowCount();
//       int c =0;
//    
//      
//       do
//           try {
//              int f = c++;
//              float n1 = Float.parseFloat(tablap.getValueAt(f, 6).toString());
//
//              String nu = LCOSTOT.getText();
//
//              double nu2;
//           nu2 = Double.parseDouble(nu);
//              float re = (float) (n1+nu2);
//              float reua,r2;
//              reua=Float.parseFloat(eua.getText());
//              r2=re*reua;
//              
//             
//              LCOSTOT.setText(String.valueOf(re));
//              LOCOSTOEU.setText(String.valueOf(r2));
//           } catch (Exception e) {
//               
//           }
//           
//           
//           while(c<ta);        // TODO add your handling code here:
    }//GEN-LAST:event_euaKeyReleased

    /**
     * @param args the command line arguments
     */
     public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUCTOS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUCTOS2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCOSTOT;
    private javax.swing.JTextField aux;
    private javax.swing.JButton btn_act;
    private javax.swing.JTextField eua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lfecha;
    private javax.swing.JLabel lhora;
    private javax.swing.JTable tablap;
    private javax.swing.JTextField txt_cla;
    private javax.swing.JTextField txt_costoeu;
    private javax.swing.JTextField txt_existencia1;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_precioto;
    private javax.swing.JTextField txt_producto;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JTextField txt_ubicacion1;
    private javax.swing.JTextField txt_uni;
    // End of variables declaration//GEN-END:variables

   
}
