
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Personal
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        grupo_botones();
        agrupaActividades();
        rb_masculino.setSelected(true);
        rb_cbi.setSelected(true);
    }
    
    public void grupo_botones(){
        buttonGroup1.add(rb_masculino);
        buttonGroup1.add(rb_femenino);
        
        buttonGroup2.add(rb_cbi);
        buttonGroup2.add(rb_csh);
        buttonGroup2.add(rb_cyad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       LinkedList<JCheckBox> actividades = new LinkedList();
       
       public void agrupaActividades(){
           actividades.add(box_encuestas);
           actividades.add(box_inscripcion);
           actividades.add(box_PERAJ);
       }
       
       public String registroActividades(LinkedList<JCheckBox> lista){
           int contador=0;
           String cadena = "";
           for(int i=0; i<lista.size(); ++i){
               JCheckBox aux = lista.get(i);
               if(aux.isSelected()){
                   cadena += aux.getText() + " ";
                   ++contador;
               }
           }
           if(contador == 0){
               cadena = "NINGUNA";
           }
           
        return cadena;
        
       }
       
       public String getGenero(){
        String genero="";
        
        if(rb_masculino.isSelected()){
            genero = rb_masculino.getLabel();
        }else if(rb_femenino.isSelected()){
            genero = rb_femenino.getLabel();
        }
           return genero;  
       }
       
       public String getDivision(){
           String division = "";
           if(rb_cbi.isSelected()){
               division = rb_cbi.getLabel();
           }else if(rb_csh.isSelected()){
               division = rb_csh.getLabel();
           }else if(rb_cyad.isSelected()){
               division = rb_cyad.getLabel();
           }
           return division;
       }
       
       public void limpiarDatos(){
            txt_matricula.setText("");
            txt_apellidoP.setText("");
            txt_apellidoM.setText("");
            txt_nombre.setText("");
            txt_edad.setText("");
            rb_cbi.setSelected(true);
            rb_masculino.setSelected(true);
            box_encuestas.setSelected(false);
            box_inscripcion.setSelected(false);
            box_PERAJ.setSelected(false);
            
           
       }
       
       public void insertar(){
           String matricula = txt_matricula.getText();
           String apellidoP = txt_apellidoP.getText().toUpperCase();
           String apellidoM = txt_apellidoM.getText().toUpperCase();
           String nombre = txt_nombre.getText().toUpperCase();
           String edad = txt_edad.getText();
           String genero = getGenero();
           String division = getDivision();
           String actividades = registroActividades(this.actividades);
           
           if(matricula.isEmpty() || apellidoP.isEmpty()|| apellidoM.isEmpty()|| nombre.isEmpty()|| edad.isEmpty()){
               JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS MARCADOS CON * SON OBLIGATORIOS", "ERROR", JOptionPane.ERROR_MESSAGE);
           }else{
           
           String sql = "INSERT INTO persona(matricula, apellidop, apellidom, nombre, edad, genero, division, actividad) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
           
        try {
            PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sql);
            pst.setString(1, matricula);
            pst.setString(2, apellidoP);
            pst.setString(3, apellidoM);
            pst.setString(4, nombre);
            pst.setString(5, edad);
            pst.setString(6, genero);
            pst.setString(7, division);
            pst.setString(8, actividades);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO", "REGISTRO", JOptionPane.INFORMATION_MESSAGE);
            limpiarDatos();
           }
       }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidoP = new javax.swing.JTextField();
        txt_apellidoM = new javax.swing.JTextField();
        txt_matricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_femenino = new javax.swing.JRadioButton();
        rb_masculino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rb_cbi = new javax.swing.JRadioButton();
        rb_csh = new javax.swing.JRadioButton();
        rb_cyad = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        box_encuestas = new javax.swing.JCheckBox();
        box_inscripcion = new javax.swing.JCheckBox();
        box_PERAJ = new javax.swing.JCheckBox();
        btn_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de actividades");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 250, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sistema de Registro de Actividades del Alumno");

        jLabel2.setText("*Nombre:");

        jLabel3.setText("*Apellido Paterno:");

        jLabel4.setText("*Apellido Materno:");

        jLabel5.setText("*Matricula:");

        txt_nombre.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setText("*Edad:");

        jLabel7.setText("*Genero:");

        rb_femenino.setText("Femenino");

        rb_masculino.setText("Masculino");

        jLabel8.setText("*División:");

        rb_cbi.setText("CBI");

        rb_csh.setText("CSH");

        rb_cyad.setText("CyAD");

        jLabel9.setText("Actividades de Interes:");

        box_encuestas.setText("Encuestas");

        box_inscripcion.setText("Procesos de Inscripción");

        box_PERAJ.setText("PERAJ");

        btn_registrar.setBackground(new java.awt.Color(204, 204, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(279, 279, 279))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txt_apellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addComponent(txt_apellidoP)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(txt_nombre)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matricula)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_masculino)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(rb_femenino))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_cbi)
                                .addGap(18, 18, 18)
                                .addComponent(rb_csh)
                                .addGap(18, 18, 18)
                                .addComponent(rb_cyad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box_encuestas)
                            .addComponent(jLabel9)
                            .addComponent(box_inscripcion)
                            .addComponent(box_PERAJ))
                        .addGap(126, 126, 126))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_apellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_apellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_femenino)
                    .addComponent(rb_masculino)
                    .addComponent(box_encuestas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(box_inscripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cbi)
                    .addComponent(rb_csh)
                    .addComponent(rb_cyad)
                    .addComponent(box_PERAJ))
                .addGap(18, 18, 18)
                .addComponent(btn_registrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        insertar();
        
        
    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box_PERAJ;
    private javax.swing.JCheckBox box_encuestas;
    private javax.swing.JCheckBox box_inscripcion;
    private javax.swing.JButton btn_registrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_cbi;
    private javax.swing.JRadioButton rb_csh;
    private javax.swing.JRadioButton rb_cyad;
    private javax.swing.JRadioButton rb_femenino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JTextField txt_apellidoM;
    private javax.swing.JTextField txt_apellidoP;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
BaseDeDatos mysql = new BaseDeDatos();
Connection cn = mysql.Connectar();
}

