
import java.util.LinkedList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Personal
 */
public class Principal extends javax.swing.JFrame {
    
    
    
  
   
   
    
   

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        asignar_grupoBotones();
        llenado_por_defecto();
        
        
        
    }
     public void asignar_grupoBotones(){
        buttonGroup1.add(radio_femenino);
        buttonGroup1.add(radio_masculino);
        
        buttonGroup2.add(rb_casado);
        buttonGroup2.add(rb_divorciado);
        buttonGroup2.add(rb_soltero);
        buttonGroup2.add(rb_libre);
        
        buttonGroup3.add(rb_mexicana);
        buttonGroup3.add(rb_extranjera);   
    }
     /* este metodo seleciona por defecto casillas y radio botones*/
     public void llenado_por_defecto(){
         txt_area.setVisible(false);
        radio_masculino.setSelected(true);
        rb_soltero.setSelected(true);
        rb_mexicana.setSelected(true);
        caja_ingles.setSelected(true);
        caja_cmas.setSelected(true);
        
     }
     
     public String getSexo(){
         String sexo = "";
         if(radio_masculino.isSelected()){
             sexo = radio_masculino.getLabel();
         }else if(radio_femenino.isSelected()){
             sexo = radio_femenino.getLabel();
         }
        return sexo;
     }
     public String getEstado(){
         String estado="";
         if(rb_soltero.isSelected()){
            estado= rb_soltero.getLabel();
         }else if(rb_casado.isSelected()){
             estado=rb_casado.getLabel();
         }else if(rb_divorciado.isSelected()){
             estado=rb_divorciado.getLabel();
         }else if(rb_libre.isSelected()){
            estado= rb_libre.getLabel();
         }
        return estado;
     }
     
     public String getbacional(){
         String nacionalidad="";
         if(rb_mexicana.isSelected()){
             nacionalidad=rb_mexicana.getLabel();
         }else{
             nacionalidad = rb_extranjera.getLabel();
         }
         return nacionalidad;
     }
     public String getidioma(){
         String lenguajes="";
         if(caja_ingles.isSelected()){
             lenguajes += caja_ingles.getLabel()+" ";
         }
        if(caja_aleman.isSelected()){
             lenguajes += caja_aleman.getLabel()+" ";
         }
        if(caja_frances.isSelected()){
             lenguajes += caja_frances.getLabel()+" ";
         }
        if(idioma_otro.isSelected()){
             lenguajes += idioma_otro.getLabel()+" ";
         }
        if(lenguajes==""){
            lenguajes = "NINGUN IDIOMA SELECIONADO";
        }
         
         return lenguajes;
     }
     public String getlenguaje(){
         String lenguaje="";
         if(caja_cmas.isSelected()){
             lenguaje += caja_cmas.getLabel() + " ";
         }
         if(caja_cshare.isSelected()){
             lenguaje += caja_cshare.getLabel() + " ";
         }
         if(caja_java.isSelected()){
             lenguaje += caja_java.getLabel() + " ";
         }
         if(caja_php.isSelected()){
             lenguaje += caja_php.getLabel() + " ";
         }
         if(lenguaje_otro.isSelected()){
             lenguaje += txt_area.getText()+" ";
         }
         if(lenguaje==""){
             lenguaje="NINGUN LENGUAJE SELECCIONADO";
         }
         return lenguaje;
     }
     
     public void mostrar_datos(){
         JOptionPane.showMessageDialog(null, "Genero: "+getSexo()+"\n"
                                            +"Estado civil: "+getEstado()+"\n"
                                            +"Nacionalidad: "+getbacional()+"\n"
                                            +"Idioma(s): "+getidioma()+"\n"
                                            +"Lenguaje(s) de programación: "+getlenguaje());
     }
     
     
    
     
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radio_masculino = new javax.swing.JRadioButton();
        radio_femenino = new javax.swing.JRadioButton();
        rb_soltero = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        rb_divorciado = new javax.swing.JRadioButton();
        rb_libre = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb_mexicana = new javax.swing.JRadioButton();
        rb_extranjera = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        caja_cmas = new javax.swing.JCheckBox();
        caja_cshare = new javax.swing.JCheckBox();
        caja_php = new javax.swing.JCheckBox();
        caja_java = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        caja_ingles = new javax.swing.JCheckBox();
        caja_frances = new javax.swing.JCheckBox();
        caja_aleman = new javax.swing.JCheckBox();
        lenguaje_otro = new javax.swing.JCheckBox();
        btn_registrar = new javax.swing.JButton();
        idioma_otro = new javax.swing.JCheckBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check boxes and radio buttons");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("ENCUESTA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Genero:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Estado civil:");

        radio_masculino.setText("Masculino");

        radio_femenino.setText("Femenino");
        radio_femenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_femeninoMouseClicked(evt);
            }
        });

        rb_soltero.setText("Soltero");

        rb_casado.setText("Casado");

        rb_divorciado.setText("Divorciado");

        rb_libre.setText("Union libre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nacionalidad:");

        rb_mexicana.setText("Mexicana");

        rb_extranjera.setText("Extranjera");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Lenguajes de programación");

        caja_cmas.setText("C++");

        caja_cshare.setText("C#");

        caja_php.setText("PHP");

        caja_java.setText("Java");

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Idiomas:");

        caja_ingles.setText("Ingles");

        caja_frances.setText("Frances");

        caja_aleman.setText("Aleman");

        lenguaje_otro.setText("Otro");
        lenguaje_otro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lenguaje_otroMouseClicked(evt);
            }
        });

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        idioma_otro.setText("Otro");
        idioma_otro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idioma_otroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(221, 221, 221))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caja_cmas)
                                .addGap(432, 432, 432)
                                .addComponent(caja_ingles))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caja_php)
                                    .addComponent(lenguaje_otro))
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(caja_java))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(481, 481, 481)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caja_aleman)
                                    .addComponent(caja_frances)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idioma_otro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_registrar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caja_cshare)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb_mexicana)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_extranjera))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb_soltero)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_casado)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_divorciado)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_libre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_masculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_femenino))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_masculino)
                    .addComponent(radio_femenino))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_soltero)
                    .addComponent(rb_casado)
                    .addComponent(rb_divorciado)
                    .addComponent(rb_libre))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_mexicana)
                    .addComponent(rb_extranjera))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caja_cmas)
                            .addComponent(caja_ingles))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caja_cshare)
                            .addComponent(caja_frances))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caja_java)
                            .addComponent(caja_aleman))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caja_php)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_registrar)
                                .addComponent(idioma_otro)))
                        .addGap(18, 18, 18)
                        .addComponent(lenguaje_otro)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idioma_otroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idioma_otroMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idioma_otroMouseClicked

    private void lenguaje_otroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lenguaje_otroMouseClicked
        // TODO add your handling code here:
        
        txt_area.setText("");
        if(lenguaje_otro.isSelected()){
            txt_area.setVisible(true);
        }else{
            txt_area.setVisible(false);
        }
    }//GEN-LAST:event_lenguaje_otroMouseClicked

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
               mostrar_datos();
        
         
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void radio_femeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_femeninoMouseClicked
       
    }//GEN-LAST:event_radio_femeninoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox caja_aleman;
    private javax.swing.JCheckBox caja_cmas;
    private javax.swing.JCheckBox caja_cshare;
    private javax.swing.JCheckBox caja_frances;
    private javax.swing.JCheckBox caja_ingles;
    private javax.swing.JCheckBox caja_java;
    private javax.swing.JCheckBox caja_php;
    private javax.swing.JCheckBox idioma_otro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox lenguaje_otro;
    private javax.swing.JRadioButton radio_femenino;
    private javax.swing.JRadioButton radio_masculino;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_divorciado;
    private javax.swing.JRadioButton rb_extranjera;
    private javax.swing.JRadioButton rb_libre;
    private javax.swing.JRadioButton rb_mexicana;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
