/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.ws.ev.formas;

import java.awt.Graphics;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.sw.ev.operaciones.LLenarTabla;

/**
 *
 * @author Personal
 */
public class Tablas extends javax.swing.JFrame {

    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
        this.setLocationRelativeTo(this);
        tablaInicial();
        llenarTabla();
        productos();
        
    }
    
    public void tablaInicial(){
        DefaultTableModel modelo = new DefaultTableModel();
        tbla_datos.setModel(modelo);
    }
    
    public void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        tbla_datos.setModel(modelo);
        
        LLenarTabla llena = new LLenarTabla();
        Vector<String> listaTitulos = new Vector();
        listaTitulos = llena.tituloColumna();
        
        for(int i=0; i<listaTitulos.size(); ++i){
            String titulo = listaTitulos.get(i);
            modelo.addColumn(titulo);
        }
        
        Vector filas = llena.elementoCelda();
        
        modelo.setDataVector(filas, listaTitulos);
        
        
    }
    
    private void productos(){
        
        int filas = tbla_datos.getRowCount();
        int columnas = tbla_datos.getColumnCount();
        int total_prod=0;
        
        int producto [][] = new int[filas][columnas];
        
        for(int i=0; i<filas; ++i){
            
            for(int j=1; j<columnas; ++j){
                
                String dato = (String) tbla_datos.getValueAt(i, j);
                if(j!=(columnas-1)){
                producto[i][j] = Integer.parseInt(dato);
                total_prod+=producto[i][j];
                //System.out.println(total_prod+"\n");
                }else{
                    int faltante = 10 - total_prod;
                    tbla_datos.setValueAt(""+faltante, i, j);
                    total_prod=0;
                }             
            }  
        } 
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbla_datos = new javax.swing.JTable();
        btn_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbla_datos.setEditingColumn(1);
        tbla_datos.setEditingRow(1);
        tbla_datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbla_datosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbla_datos);

        btn_calcular.setText("Recalcular ");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        
        productos();
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void tbla_datosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbla_datosKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbla_datosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbla_datos;
    // End of variables declaration//GEN-END:variables
}
