/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.selecciones.formas;


import java.util.LinkedList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import uam.pvoe.sw.selecciones.clases.Alumno;
import uam.pvoe.sw.selecciones.clases.Licenciatura;
import uam.pvoe.sw.selecciones.clases.Opcion;
import uam.pvoe.sw.selecciones.negocio.AdministrarAlumnos;
import uam.pvoe.sw.selecciones.negocio.AdministrarLicenciaturas;




/**
 *
 * @author
 */
public class FrmSeleccionesObjetos extends javax.swing.JFrame {

    LinkedList<JCheckBox>listaChkBoxes = new LinkedList();
    
    /**
     * Creates new form FrmSeleccionesObjetos
     */
        public FrmSeleccionesObjetos() {
            initComponents();
            agruparSelecciones();
            agruparChkBoxes();
            cmbListaAlumnos.removeAllItems();
            cmbListaLicenciaturas.removeAllItems();
            llenarLicenciaturas();
        }
        
        public void llenarLicenciaturas(){
            AdministrarLicenciaturas l1 = new AdministrarLicenciaturas();
            LinkedList<Licenciatura> lista = l1.listaLicenciaturas();
            for(int i=0; i<lista.size(); ++i){
                Licenciatura lic = new Licenciatura();
                lic=lista.get(i);
               cmbListaLicenciaturas.addItem(lic);
            }
        }
        
        public void llenarAlumnos(String clave){
            AdministrarAlumnos administra = new AdministrarAlumnos();
            LinkedList<Alumno>lista = administra.listaPorCarrera(clave);
            cmbListaAlumnos.removeAllItems();
            for(int i=0; i<lista.size(); ++i){
                Alumno alumno = lista.get(i);
                cmbListaAlumnos.addItem(alumno);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpApoyo = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblLicenciatura = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        cmbListaLicenciaturas = new javax.swing.JComboBox<>();
        cmbListaAlumnos = new javax.swing.JComboBox<>();
        btnMerece = new javax.swing.JRadioButton();
        btnNoMerece = new javax.swing.JRadioButton();
        chkPronabe = new javax.swing.JCheckBox();
        chkUam = new javax.swing.JCheckBox();
        chkCDMX = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        lblTitulo.setText("Sistema de Apoyos Económicos para Alumnos");

        lblLicenciatura.setText("Selecciona la Licenciatura");

        lblAlumno.setText("Selecciona el Alumno");

        cmbListaLicenciaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaLicenciaturasActionPerformed(evt);
            }
        });

        btnMerece.setText("jRadioButton1");

        btnNoMerece.setText("jRadioButton1");

        chkPronabe.setText("jCheckBox1");

        chkUam.setText("jCheckBox1");

        chkCDMX.setText("jCheckBox1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo)
                        .addComponent(lblLicenciatura)
                        .addComponent(lblAlumno)
                        .addComponent(cmbListaLicenciaturas, 0, 344, Short.MAX_VALUE)
                        .addComponent(cmbListaAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMerece)
                            .addComponent(btnNoMerece))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCDMX)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkPronabe)
                                .addGap(53, 53, 53)
                                .addComponent(chkUam)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addComponent(lblLicenciatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbListaLicenciaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblAlumno)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnMerece))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPronabe)
                            .addComponent(chkUam))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoMerece)
                    .addComponent(chkCDMX))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListaLicenciaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaLicenciaturasActionPerformed
        // TODO add your handling code here:
        Licenciatura licenciatura = (Licenciatura) cmbListaLicenciaturas.getSelectedItem();
        //JOptionPane.showMessageDialog(rootPane, licenciatura.getClave());
        llenarAlumnos(licenciatura.getClave());
    }//GEN-LAST:event_cmbListaLicenciaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeleccionesObjetos().setVisible(true);
            }
        });
    }
    
    /*Agrupa los Radio Buttons*/
    public void agruparSelecciones(){
        btnGrpApoyo.add(btnMerece);
        btnGrpApoyo.add(btnNoMerece);
       
    }
    
    /*Agrupa los CheckBoxes*/
    public void agruparChkBoxes(){
        listaChkBoxes.add(chkUam);
        listaChkBoxes.add(chkCDMX);
        listaChkBoxes.add(chkPronabe);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpApoyo;
    private javax.swing.JRadioButton btnMerece;
    private javax.swing.JRadioButton btnNoMerece;
    private javax.swing.JCheckBox chkCDMX;
    private javax.swing.JCheckBox chkPronabe;
    private javax.swing.JCheckBox chkUam;
    private javax.swing.JComboBox<Alumno> cmbListaAlumnos;
    private javax.swing.JComboBox<Licenciatura> cmbListaLicenciaturas;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblLicenciatura;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
